author: Rui Ribeiro

github_username:  ruialexrib
github_show_profile_link: true

social-network-links:
  linkedin: ruialexrib
  github: ruialexrib
  
share-links-active:
  twitter: true
  facebook: true
  linkedin: true
  vk: false

theme: jekyll-theme-cayman
