author: Rui Ribeiro
title: SAFTReader.PT
description: O software SAFT READER permite visualizar, validar e analisar os dados do Ficheiro SAF-T PT, no formato 1.04_01 (Portaria n.ยบ 302/2016, de 2 de dezembro), criado a partir de qualquer programa, relativos a documentos de venda, tabelas de impostos, clientes e produtos.


theme: jekyll-theme-cayman
